name: pifia_env
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - numpy
  - pandas
  - tensorflow==2.1.0
  - pip:
    - pillow==6.1.0
    - plotly==4.14.3
    - seaborn==0.11.1
